# Generated by Django 5.2.3 on 2025-06-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_blog_writer_alter_reviews_review_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='review_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='review_updated',
            new_name='updated',
        ),
    ]
